version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: tekkromancer/get-started:part1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        # condition: on-failure
        condition: unless-stopped
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
